GET http://localhost:3001/api/persons/1
###
GET http://localhost:3001/api/persons
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Stepahnie",
  "number": 300030003000
}
###
PUT http://localhost:3001/api/persons/60343bf152c85219ceab57f4
Content-Type: application/json

{
  "name": "sadb",
  "number": 578948932154
}

###
DELETE http://localhost:3001/api/persons/1
Content-Type: application/json

{
  "id": 1
}